### ISSUE TITLE
Alternate registration flow

### ISSUE THREAD

**Issue by jakearchibald** [marcoscaceres/payment-request-handler#2]
This might be a little closer to other service worker APIs:

```js
// This is the point permission is asked, if not already granted.
// If the app is already registered, it returns the existing app.
const paymentApp = await registration.payments.registerApp();

await paymentApp.methods.set(key, opts);
```

**Comment by jakearchibald** [comment]
You could hang other methods off `paymentApp` like `paymentApp.unregister()`.

This removes the need for a separate `requestPermission` method.

**Comment by marcoscaceres** [comment]
Good suggestion... wanted to avoid using the word "app" (as this is just a feature), but will add .register() and .unregister().
