### ISSUE TITLE
Async respondWith

### ISSUE THREAD

**Issue by jakearchibald** [marcoscaceres/payment-request-handler#7]
One of the examples calls `ev.respondWith` async, as in after the initial dispatch of the event. This isn't allowed in the fetch event, and payments might want to align with that.

How it works with fetch:

```js
addEventListener('fetch', event => {
  event.respondWith((async () => {
    const response = await getResponseSomehow();

    // do additional async work
    event.waitUntil((async () => {
      const responseClone = response.clone();
      await cacheResponseSomehow(responseClone);
    })());

    return response;
  })());
});
```

As in, `respondWith` must be called within the dispatch of the event, but `waitUntil` can be called as long as other promises passed to `waitUntil`/`respondWith` haven't settled.

**Comment by marcoscaceres** [comment]
Ah yeah, of course... will move the function out into a "task". I find the whole self-invoking anonymous async functions a little hard on the eyes.

**Comment by marcoscaceres** [comment]
@jakearchibald, inverted the code, based on your feedback. now .respondWith() first, and ev.waitUntil() later.

**Comment by marcoscaceres** [comment]
Fixed a bunch of silly bugs too. Still probably buggy... but a bit better.
